### ISSUE TITLE
Parse DipTrace drill file coordinate format

### ISSUE THREAD

**Issue by galacticstudios** [tracespace/tracespace#137]
Consider the attached [Gerber](https://github.com/tracespace/tracespace/files/2994023/5c81b97d6556290abe26cca6e11bbdbb.zip). It comes from [OSH Park](https://oshpark.com/shared_projects/DSenh4Ol) and here's its "official" rendering:
![4b0636e2b8fd6d7b3ad5ec75e8696597](https://user-images.githubusercontent.com/13740036/54786493-5f5a2e00-4bff-11e9-8a17-3ce700337a37.png)

But pcbStackup renders it thusly
![top](https://user-images.githubusercontent.com/13740036/54786338-fbd00080-4bfe-11e9-8acc-cc658c288a1d.png)

Notice the white area in the lower left. Also, there are no drill holes in the pads. I suspect the drills are getting misplaced in the corner.

**Comment by mcous** [comment]
The coordinate format for the drill file in this board package is 4.2. The default for drill files in metric is 3.3. Using [tracespace view](https://tracespace.io/view) and setting "override drill integer/decimal coordinate format" in the board settings to 4.2 results in the correct render.

Unlike Gerber files, drill files do not have an established mechanism to specify their coordinate format. That being said, it looks like DipTrace is adding a non-standard format callout to its unit setting:

```
METRIC,0000.00
```

Adding that to gerber-parser is totally doable
