### ISSUE TITLE
Return a list of apertures and drills

### ISSUE THREAD

**Issue by galacticstudios** [tracespace/tracespace#139]
It would be nice if the object returned by pcbStackup provided a way to enumerate the drills and apertures. This would allow a user to find the minimum drill size and trace width, which are important when quoting PCB manufacturing prices.

**Comment by mcous** [comment]
@kasbah and I were discussing this in #52, so I've updated that ticket to track our manufacturing stats collection efforts. Gonna close this issue in favor of following it there, but thanks for the request!
