### ISSUE TITLE
Publish `<script>` bundles to npm (for usage with unpkg)

### ISSUE THREAD

**Issue by mcous** [tracespace/tracespace#178]
As a potential tracespace user, I would like to be able to try the libraries out (or use them) via a `<script>` tag so that I don't need a bundler in my workflow if I don't want to.

We should publish bundles for the following libraries:

- gerber-parser
- gerber-plotter
- gerber-to-svg
- whats-that-gerber
- pcb-stackup-core
- pcb-stackup

Thanks to @galacticstudios for the request!

**Comment by galacticstudios** [comment]
Publishing <script> bundles is one approach. Another, perhaps better one, would be to write up a dummies guide to bundling up the libraries. It's like the old saying about teaching a man to fish.

**Comment by mcous** [comment]
More concrete browser usage examples in the docs is a good idea. Will definitely make it a priority
