### ISSUE TITLE
wtg: Support PCB:NG's conventions

### ISSUE THREAD

**Issue by kasbah** [tracespace/tracespace#246]
From https://github.com/kitspace/kitspace/pull/148. The project uses Eagle with [this CAM job](https://support.pcb.ng/support/solutions/articles/9000075420-for-eagle-users). 

Example: https://tracespace.io/view/?boardUrl=https://cloud.monostable.co.uk/openbadge.zip

**Comment by mcous** [comment]
These are very sane conventions that should be easy to match on
