### ISSUE TITLE
How to convert PCB ASCII File Format  to Gerber File in linux server？

### ISSUE THREAD

**Issue by aaronbo2019** [tracespace/tracespace#260]
How to convert PCB ASCII File Format  to Gerber File in linux server？I want to view the svg image in browser, when I have uploaded the PCB ASCII File Format.

**Comment by mcous** [comment]
@aaronbo2019 what is the "PCB ASCII File Format"? I googled it and it looks like you may be referring to a proprietary Altium CAD file format  If this is the case, then I'm afraid we can't help, because generating Gerber output from a CAD file is way outside the scope of tracespace

**Comment by aaronbo2019** [comment]
@mcous yes, maka sure it is Altium CAD file. I close the issue.

**Comment by aaronbo2019** [comment]
@mcous yes, maka sure it is Altium CAD file. I close the issue.
