### ISSUE TITLE
Layer re-use in board render causes problems when layers have clear layers

### ISSUE THREAD

**Issue by attie** [tracespace/tracespace#303]
I don't _think_ this is the same as #302, but it may be... (it has different characteristics, but I'm leaning towards incorrect SVG Paths for both).

It seems that any / all silkscreen has filled voids that are rendered incorrectly in the "_top_" and "_bottom_" views... However the "_layers_" view and exported SVGs are fine.

These gerbers are produced using Altium Designer.

![image](https://user-images.githubusercontent.com/2195519/66435695-586cfe80-ea1d-11e9-9965-340addb1fb12.png)

![image](https://user-images.githubusercontent.com/2195519/66436081-24dea400-ea1e-11e9-9827-a1df236c716a.png)

[board.zip](https://github.com/tracespace/tracespace/files/3704640/board.zip)

**Comment by mcous** [comment]
Thanks for the report! This is an interesting one. After investigation:

- The Gerber files in this issue and #302 use a combination of draws and clears (at the Gerber level) via `%LPD%*` and `%LPC%*` 
- tracespace re-creates these draw and clear layers using SVG masks
- As an optimation, tracespace view attempts to re-use the layer renders in the board renders with SVG `<use>` elements

These boards render correctly with the [tracespace CLI](https://github.com/tracespace/tracespace/tree/master/packages/cli), which _does not_ attempt to re-use anything. So it looks the online viewer may need to ditch the layer re-use

(The SVG paths, if you're curious, are not related. Gerber, in essence, is a vector image format. Most of what this library does is convert Gerber constructs directly into SVG constructs. tracespace takes Gerber "traces" and turns them into SVG `<path>`s, where (generally) there will be one `<path>` element for all the traces the Gerber file draws with a given tool before it changes the tool or changes the region mode)

**Comment by attie** [comment]
Thanks for the update - I hope you don't mind if I leave this in your capable hands to resolve... please let me know if you'd like any additional files / testing.

**Comment by mcous** [comment]
Fix for this issue was released in v4.2.0!
