### ISSUE TITLE
PCBA rendering

### ISSUE THREAD

**Issue by faisalil** [tracespace/tracespace#312]
Can the project be used to render PCBA boards; i.e. assembled boards? currently, what I saw is the rendering of plain boards with no components.

**Comment by mcous** [comment]
Thanks for the question @faisalil! Unfortunately, I don't have any plans to render anything other than Gerber and drill files at this time.

I'm gonna leave this issue open for now in case you (or anyone else) has ideas about how PCBA rendering could be accomplished. Off the top of my head, we'd require:

- PnP CSV file parsing
    - Is there a we'll established standard here?
- Some sort of parts library
    - I wonder if there's existing work in this area we could leverage?
