### ISSUE TITLE
How to convert one Gerber file to SVG via CLI?

### ISSUE THREAD

**Issue by andygock** [tracespace/tracespace#327]
Can you use this tool to convert one gerber file to one SVG via CLI?

I've tried with no success. On a Windows machine, I keep receiving response `Error: No valid Gerber or drill files found` when issuing command `tracespace -B --force sample.gbr`. I get the same error regardless of whether `sample.gbr` exists or not.

Am I missing someone simple here?

What's an example command to convert a single gerber to SVG?

Thanks.

**Comment by mcous** [comment]
Well this is embarrassing! The command you posted is correct (and the `--force` isn't necessary), except for the fact that input file path resolution is completely broken on Windows.

Fix incoming

**Comment by mcous** [comment]
Fix released with v4.2.1
