### ISSUE TITLE
pcb-stackup-core output 

### ISSUE THREAD

**Issue by sangameshBappanna** [tracespace/tracespace#340]
Hi,
I am using pcb-stackup-core, I am getting all layer SVG other than **".ger, .drd, .prb, .prc"**
For a drill file, I am able to see only drills in SVG not the layer.

**Comment by mcous** [comment]
@sangameshBappanna the `pcb-stackup` and `pcb-stackup-core` libraries always generate full PCB renders. If you want to generate individual layer renders, you need to use `gerber-to-svg`.

The `@tracespace/cli` tool uses both `pcb-stackup` and `gerber-to-svg` together to output PCB renders and layer renders at the same time. I would recommend reading the source code to see how you can take the `layers` output of `pcb-stackup` and send it back into the static `gerberToSvg.render` method to render individual layers from your stackup

https://github.com/tracespace/tracespace/blob/main/packages/cli/lib/cli.js
