### ISSUE TITLE
pcb-stackup-core issue with type drawing

### ISSUE THREAD

**Issue by sangameshBappanna** [tracespace/tracespace#343]
Hi, when I use a .GBR in pcb-stackup-core it is giving SVG output but it contains a <rect> tag with width and height but nothing inside.
my main task here is to render layers as done in tracespace.io/view layer
my output when I use pcb-stackup-core library
![image](https://user-images.githubusercontent.com/36264958/89282993-052e0180-d66a-11ea-95c2-c53002f929f7.png)

https://tracespace.io/view/ Output 
![image](https://user-images.githubusercontent.com/36264958/89283070-27c01a80-d66a-11ea-8274-bc2494fd91a0.png)

I don't understand why I am not seeing 
"drawing l01_global_track.GBR" in my output 

Please help me in this issue.

**Comment by mcous** [comment]
The `"layers" view of the tracespace viewer is produced by the `gerber-to-svg` library, not `pcb-stackup-core`. 

- `gerber-to-svg`: produces layer renders in SVG
- `pcb-stackup-core`: takes the layer renders from `gerber-to-svg` and produces top and bottom board renders

If you want a single SVG with all your layers simply printed (i.e. not rendered as a PCB would look), you would need to take the outputs of `gerber-to-svg` and combine them into a single SVG yourself. This file shows how tracespace view creates that single layers SVG: https://github.com/tracespace/tracespace/blob/main/apps/view/src/BoardDisplay/LayersRender.tsx
