### ISSUE TITLE
Not properly rendering PCB without Top Solderpaste Layer

### ISSUE THREAD

**Issue by geocine** [tracespace/tracespace#347]
I created a PCB without a Top Solderpaste Layer. https://www.dropbox.com/s/2awgshmhyykhyiu/Gerber_Phantom%20PCB.zip?dl=1

This is not properly being rendered on  tracespace.io, this is how it looks:

![](https://i.imgur.com/T9fggHt.png)

This is how it looks on another renderer

![](https://i.imgur.com/pH9oIvf.png)

**Comment by mcous** [comment]
Thanks for the report @geocine! Looking at your outline layer, there look to be little gaps between some of the round corners and the straight edges, which cause the board shape fill to go weird.

The current iteration of tracespace is pretty naive in how it shows the board shape: it tries to translate the outline Gerber directly to SVG (with some gap filling and path reordering) and hopes that SVG fills in the shape properly. If the shape has gaps, it will _not_ fill properly.

I'm hoping to get something more robust in place eventually, but for now, you can get this board to render properly by setting the "gap fill limit" to `0.85 mm` or higher in the board render settings (see [this section of the troublehshooting guide](https://github.com/tracespace/tracespace/blob/main/apps/view/HELP.md#no-image-or-incorrect-board-shape)).
