### ISSUE TITLE
Recognising non-copper layer as copper layer

### ISSUE THREAD

**Issue by Upendrasengar** [tracespace/tracespace#374]
It's is happening for some files where it is provided with non-copper layer files but in JSON we see the type is a copper layer.  Not sure if it is earlier mentioned or not but this has been a long-running issue for me.

Any insight would be helpful.

**Comment by kasbah** [comment]
Seems like the same issue as https://github.com/tracespace/tracespace/issues/357, if you have specific examples please add them there.

**Comment by Upendrasengar** [comment]
@kasbah thanks for the response.
can you please help me identify the issue, I'm attaching the file if you can please verify
[test-file.zip](https://github.com/tracespace/tracespace/files/8107202/test-file.zip)
?

**Comment by Upendrasengar** [comment]
@kasbah can you please update anything here?
