### ISSUE TITLE
Board size calculation error

### ISSUE THREAD

**Issue by shawon1220** [tracespace/tracespace#386]
When dimensions are included，Board size calculation error.
[gerber_test.zip](https://github.com/tracespace/tracespace/files/9010749/gerber_test.zip)

**Comment by mcous** [comment]
The viewer is only able to render a board shape if there is a "board outline" Gerber layer than contains the outline as a path and nothing else. I do not see such a file included with this board, so the fallback behavior of rendering the smallest board that fits everything included in every given Gerber file is expected

**Comment by shawon1220** [comment]
![image](https://user-images.githubusercontent.com/10345404/176712576-e290a12e-8e65-4438-8545-b3c60107dda5.png)

[gerber_HY3108-MAB1362 V1.3 20210525.zip](https://github.com/tracespace/tracespace/files/9020999/gerber_HY3108-MAB1362.V1.3.20210525.zip)
@mcous  This gerber file contains the outline layer，also with annotations. Is there any good way to calculate the dimensions excluding the marked part? Thanks .  This is a good site for uploading gerber files for quotes： https://www.pcbway.com/QuickOrderOnline.aspx

**Comment by mcous** [comment]
No, unfortunately the Gerber file format does not contain enough structured information to easily identify which parts are board outline and which parts of a given file are annotations. I do not intend to try to support anything other than pure outline layers.

This aligns with recommendations from other fabs, like [OSHPark](https://docs.oshpark.com/troubleshooting/board-outline-issues/)
