### ISSUE TITLE
How do I align the layers?

### ISSUE THREAD

**Issue by sdiricco-move** [tracespace/tracespace#387]
How can i align layers in an easy way?

**Comment by mcous** [comment]
It's not currently very easy, but you can rely on the fact that every layer is rendered in the same coordinate system. The way the the [viewer](https://tracespace.io/view) does it is:

1. Add up the `viewBox` of each layer to get a board `viewBox`
    - Alternatively: use the `viewBox` of the outline layer
2. Create a new `svg` element using that board `viewBox`
3. Copy the contents of each layer into the new SVG

When the contents of all the individual layer SVGs are placed into the same SVG with the board `viewBox`, they will be aligned.

For reference, you can see the source code of the viewer app's [`LayersRender` component](https://github.com/tracespace/tracespace/blob/49c9a22addccc70c1d1a830a9225328a91942080/apps/view/src/BoardDisplay/LayersRender.tsx)
