### ISSUE TITLE
Error: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by Luisonson** [tracespace/tracespace#415]
I'm trying to render an external zip and I always get the same error:
Error: NetworkError when attempting to fetch resource.
For example:
https://tracespace.io/view/?boardUrl=https://www.libreservo.com/sites/libreservo.com/files/Gerber/LibreServo_v3.2.zip

Is there something wrong with my URL?

Thanks for your time and effort.

**Comment by kasbah** [comment]
likely the server serving the zip URL needs to enable CORS

**Comment by Luisonson** [comment]
Yes, should be that. Thank you!
