### ISSUE TITLE
filled copper area traces are missing

### ISSUE THREAD

**Issue by shernandezsunstone** [tracespace/tracespace#416]
[OrionFinished.zip](https://github.com/tracespace/tracespace/files/10786149/OrionFinished.zip)

The attached file has a filled copper area on the left side, but all of the traces, pads, and clearances are missing.

**Comment by shernandezsunstone** [comment]
There were some deprecated items in the gerbers. I cleaned them out of my gerbers before loading and they show up perfectly.

**Comment by mcous** [comment]
Ah interesting! Generally, I'd like tracespace to ignore deprecated or unknown constructs - where reasonable - rather than fail to render properly.

What were the commands you noticed and removed?
