### ISSUE TITLE
Upgrade whats-that-gerber to 3.0.0

### ISSUE THREAD

**Issue by ju5t** [tracespace/tracespace#55]
As soon as `whats-that-gerber` 3.0.0 is released we should update it in `pcb-stackup` too.

Reference: https://github.com/tracespace/whats-that-gerber/pull/20

**Comment by mcous** [comment]
New monorepo ensures `pcb-stackup`, `whats-that-gerber`, etc. will all be kept in sync by default, and they are currently in sync on their `next` npm tags 🎂
