### ISSUE TITLE
Altium internal planes

### ISSUE THREAD

**Issue by ju5t** [tracespace/tracespace#67]
According to the [Altium documentation](https://www.altium.com/documentation/18.0/display/ADES/WorkspaceManager_Dlg-GerberSetup_Form((Gerber+Setup))_AD) internal planes can have an extension of GP[0-9]. I would personally match them in the `icu` layer and change the regex of `(g)` to `(gp?)`.

Code ref: [index.js#L80](https://github.com/tracespace/tracespace/blob/next/packages/whats-that-gerber/index.js#L80)
Issue ref: https://github.com/tracespace/whats-that-gerber/issues/23

**Comment by mcous** [comment]
Fixed in `pcb-stackup@4.0.0-next.10`, `whats-that-gerber@4.0.0-next.10`, and `@tracespace/fixtures@4.0.0-next.10`! Appreciate the PR
