### ISSUE TITLE
Altium mechanical layers in double digits

### ISSUE THREAD

**Issue by ju5t** [tracespace/tracespace#69]
The other day we received Altium files that included a .gm15-extension. At the moment it only matches single digits with `(gm[l\d]$`. Changing this to `(gm[l\d]{1,2}$` solves it for us. Do you think there would be any reason not to match two digits in this case?

I can of course send a PR for this.

Code ref: [index.js#L87](https://github.com/tracespace/tracespace/blob/next/packages/whats-that-gerber/index.js#L87)

**Comment by mcous** [comment]
Released on `pcb-stackup@next`, `whats-that-gerber@next`, and `@tracespace/fixtures@next`
