### ISSUE TITLE
Periods inside classnames require escaping

### ISSUE THREAD

**Issue by ldstein** [tracespace/tracespace#78]
Hi,

I noticed PCB Stackup will intermittently output an invalid SVG. Depending on the browser/SVG viewer, it will display either as a black or blank image.

It appears to be caused by  `shortId.generate()` occasionally returning a string which starts with a numeric character. For example "0C3Vwf2nt". 

XML IDs aren't allowed to start with a numeric character, causing the SVG viewer to misbehave.

**Comment by mcous** [comment]
Good catch! Fairly embarrassing oversight on my part. Related to tracespace/gerber-to-svg#41 (ID sanitization) and will fix them both up together

**Comment by davidworkman9** [comment]
v4.0.0-next.13 still has this problem. It's caused by a period in the ID now instead of starting with a number.
<img width="365" alt="screen shot 2018-10-12 at 11 49 11 am" src="https://user-images.githubusercontent.com/1152186/46879855-1c588b00-ce15-11e8-814a-d3f96e1505a3.png">

**Comment by mcous** [comment]
Oh shoot. Period in the ID is a valid XML ID but period inside a class name without escaping it is not. Sorry for missing that

**Comment by mcous** [comment]
Fix released to:

```
@tracespace/xml-id@4.0.0-next.14
gerber-to-svg@4.0.0-next.14
pcb-stackup-core@4.0.0-next.14
pcb-stackup@4.0.0-next.14
@tracespace/cli@4.0.0-next.14
```
