### ISSUE TITLE
Compatibility problem of '<mask>' element in svg files

### ISSUE THREAD

**Issue by anti-destiny** [tracespace/tracespace#98]
I converted a gerber file to svg and open it with Inkscape editor. In Inkscape, some "mask"s disappeared. The wrong image is here.  

| Inkscape (wrong) | Chrome (good) |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/24856363/50815352-d057ac80-1357-11e9-9f3f-f8612303a0ad.png) | ![image](https://user-images.githubusercontent.com/24856363/50815385-ebc2b780-1357-11e9-9899-cbc524b06a53.png) |  

Finally I found that inserting a "\<g\>" tag between "\<mask\>" tag and its children can fix this problem. I changed the 30th line of "packages/gerber-to-svg/lib/_utils.js":

```
  //return element('mask', attributes, children) 
  return element('mask', attributes, [element('g', {}, children)])
```

Hope my code will help you.

**Comment by mcous** [comment]
Thanks for the report @anti-destiny! Looks like we're running into https://bugs.launchpad.net/inkscape/+bug/794472 (see similar thread in #29).

I'd accept a PR for this, otherwise I'll get to it myself soon
